### ISSUE TITLE
Can't Run "from pwn import *" from Python IDLE

### ISSUE THREAD

**Issue by iamdejan** [arthaud/python3-pwntools#4]
When I run 

> from pwn import *

from Python 3.5 IDLE, it gives me error message like:
> Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from pwn import *
  File "/home/dejanosky/Downloads/python3-pwntools/pwn/__init__.py", line 2, in <module>
    from .toplevel import *
  File "/home/dejanosky/Downloads/python3-pwntools/pwn/toplevel.py", line 19, in <module>
    import pwnlib
  File "/home/dejanosky/Downloads/python3-pwntools/pwnlib/__init__.py", line 37, in <module>
    importlib.import_module('.%s' % module, 'pwnlib')
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/dejanosky/Downloads/python3-pwntools/pwnlib/args.py", line 7, in <module>
    from . import term
  File "/home/dejanosky/Downloads/python3-pwntools/pwnlib/term/__init__.py", line 5, in <module>
    from . import readline
  File "/home/dejanosky/Downloads/python3-pwntools/pwnlib/term/readline.py", line 3, in <module>
    from . import term
  File "/home/dejanosky/Downloads/python3-pwntools/pwnlib/term/term.py", line 30, in <module>
    fd = sys.stdout.buffer
AttributeError: 'PseudoOutputFile' object has no attribute 'buffer'

(dejanosky is my username).
What should I do? Thx.

**Comment by arthaud** [comment]
Hi @iamdejan 

python3-pwntools uses `sys.stdout.buffer.write()` to write bytes on the standard output (`sys.stdout.write()` only takes strings). See https://stackoverflow.com/questions/908331/how-to-write-binary-data-in-stdout-in-python-3

It looks like IDLE doesn't provide `sys.stdout.buffer`.

We would need to find another way to write bytes on the standard output (maybe `fd = os.fdopen(1, 'rb')`) and fix the code.

As a short-term solution, you can try:
```
import sys
import os
sys.stdout.buffer = os.fdopen(1, 'wb')
from pwn import *
```

**Comment by iamdejan** [comment]
ok, thx for the solution.

_Sent from my Asus ASUS_X007D using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by iamdejan** [comment]
now I get this error:
`Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    from pwn import *
  File "/home/dejanosky/Downloads/python3-pwntools/pwn/__init__.py", line 2, in <module>
    from .toplevel import *
  File "/home/dejanosky/Downloads/python3-pwntools/pwn/toplevel.py", line 19, in <module>
    import pwnlib
  File "/home/dejanosky/Downloads/python3-pwntools/pwnlib/__init__.py", line 37, in <module>
    importlib.import_module('.%s' % module, 'pwnlib')
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/dejanosky/Downloads/python3-pwntools/pwnlib/args.py", line 7, in <module>
    from . import term
  File "/home/dejanosky/Downloads/python3-pwntools/pwnlib/term/__init__.py", line 5, in <module>
    from . import readline
  File "/home/dejanosky/Downloads/python3-pwntools/pwnlib/term/readline.py", line 4, in <module>
    from . import text
  File "/home/dejanosky/Downloads/python3-pwntools/pwnlib/term/text.py", line 125, in <module>
    sys.modules[__name__] = Module()
  File "/home/dejanosky/Downloads/python3-pwntools/pwnlib/term/text.py", line 28, in __init__
    self.num_colors = termcap.get('colors', default=8)
  File "/home/dejanosky/Downloads/python3-pwntools/pwnlib/term/termcap.py", line 23, in get
    s = curses.tigetstr(cap)
_curses.error: must call (at least) setupterm() first`

**Comment by Asmeble** [comment]
Have you tried rolling back the "setuptools" package?
maybe try "pip3 install 'setuptools<=20.6' ", installing pwntools, and updating after install?


https://github.com/gsnedders/html5lib-python/commit/1603fe851d4f69699d0a9294ac75205a9a4dcde7
